apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dgyti7f06-nodejs-gitops
  description: This is GitOps manifest for dgyti7f06-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: dgyti7f06-nodejs
    janus-idp.io/tekton: dgyti7f06-nodejs
    backstage.io/kubernetes-id: dgyti7f06-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dgyti7f06-nodejs
