apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dgyti7f06-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dgyti7f06-nodejs 
  name: dgyti7f06-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dgyti7f06-nodejs 
